# Preprocessing
Preprocess data frames from original stat result files.
This notebook is used to look inside the data while preprocessing. 
Actual preprocessing is done in `mininet_vsomeip_dnssec/dataset.py`.

In [296]:
# import sys
# !{sys.executable} -m pip install --quiet polars
# !{sys.executable} -m pip install --quiet matplotlib

In [297]:
# imports and packages
import polars as pl
import os
import ipaddress

# pl.Config.set_tbl_cols(-1)
# pl.Config.set_tbl_rows(-1)

In [ ]:
PROJ_ROOT = ".."
DATA_ROOT = f"{PROJ_ROOT}/data"
RUN_DATE = "20260418-000722"
DATA_RAW = f"{DATA_ROOT}/raw"
DATA_INTERIM = f"{DATA_ROOT}/interim"
DATA_PROCESSED = f"{DATA_ROOT}/processed"
DATA_RAW_CARNET = f"{DATA_RAW}/{RUN_DATE}/carnet"
DATA_RAW_SCALABILITY = f"{DATA_RAW}/{RUN_DATE}/scalability"

## File and name logic and listing raw files
file listings create a nested map of scenario -> series -> config -> run -> service -> file path, e.g. 'carnet': {'H': {'p212_s448': {'17': {'6019': '/home/vm-user/workspace/mininet-vsomeip-evaluation/evaluation/data/raw/20260418-000722/carnet/H-series/run-17/H-6019-#0.csv'}}}}}

In [ ]:
def get_config_for_pubsub_count(pub_count, sub_count):
    return f"p{pub_count}_s{sub_count}"

def get_pubsub_count_from_config(config):
    # Assuming config format is "p{PUBCOUNT}_s{SUBCOUNT}"
    parts = config.split('_')
    pub_count = int(parts[0][1:])  # Extract PUBCOUNT
    sub_count = int(parts[1][1:])  # Extract SUBCOUNT
    return pub_count, sub_count

def find_files_for_series_and_runs_carnet(raw):
    # folder structure in raw dirs is {SERIES}-series/run-{RUN}/files
    # 1. list series folders
    series_folders = [d for d in os.listdir(raw) if (os.path.isdir(os.path.join(raw, d)) and d.endswith('-series'))]
    series_map = {}
    for series in series_folders:
        series_name = series.split('-')[0]  # Extract SERIES
        # No config level in carnet, so use predefined config name based on known pub/sub counts
        config_map = {get_config_for_pubsub_count(212, 448): _find_files_per_run(os.path.join(raw, series))}  
        series_map[series_name] = config_map
    return {"carnet": series_map} ## add a scenario level to be consistent with scalability data structure

def find_files_for_series_and_runs_scalability(raw):
    # folder structure in raw dirs is {scenario}/{SERIES}-series/run-{RUN}/{config}/files
    # 1. list scenario folders
    scenario_folders = [d for d in os.listdir(raw) if os.path.isdir(os.path.join(raw, d))]
    scenario_map = {}
    for scenario in scenario_folders:
        scenario_path = os.path.join(raw, scenario)
        # 2. list series folders
        series_folders = [d for d in os.listdir(scenario_path) if (os.path.isdir(os.path.join(scenario_path, d)) and d.endswith('-series'))]
        series_map = {}
        for series in series_folders:
            series_name = series.split('-')[0]  # Extract SERIES
            config_folders = [d for d in os.listdir(os.path.join(scenario_path, series)) if os.path.isdir(os.path.join(scenario_path, series, d))]
            config_map = {}
            for config in config_folders:
                config_map[config] = _find_files_per_run(os.path.join(scenario_path, series, config))
            series_map[series_name] = config_map
        scenario_map[scenario] = series_map
    return scenario_map

def _find_files_per_run(raw):
    # list files and parse as map run -> map service -> file path
    # 1. list runs in raw/run-{RUN}
    run_folders = [d for d in os.listdir(raw) if (os.path.isdir(os.path.join(raw, d)) and d.startswith('run-'))]
    run_map = {}
    for run in run_folders:
        run_num = run.split('-')[1]  # Extract RUN
        run_map[run_num] = _find_files_per_service(os.path.join(raw, run))
    return run_map

def _find_files_per_service(raw):
    # list files per run and parse as map service -> file path
    # 1. list files in raw dir
    files = [f for f in os.listdir(raw) if (os.path.isfile(os.path.join(raw, f)) and f.endswith('.csv'))]
    # 2. parse file names to extract service name
    service_map = {}
    for f in files:
        # Assuming file name format is "A-SERVICEID-#0.csv"
        service_name = f.split('-')[1]  # Extract SERVICEID
        service_map[service_name] = os.path.join(raw, f)
    # 3. return map service -> file path
    return service_map

In [ ]:
carnet_files = find_files_for_series_and_runs_carnet(DATA_RAW_CARNET)
carnet_files

{'carnet': {'H': {'p212_s448': {'17': {'6019': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6019-#0.csv',
     '2113': '../data/raw/20260418-000722/carnet/H-series/run-17/H-2113-#0.csv',
     '6035': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6035-#0.csv',
     '3007': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3007-#0.csv',
     '7007': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7007-#0.csv',
     '4024': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4024-#0.csv',
     '3042': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3042-#0.csv',
     '6075': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6075-#0.csv',
     '6070': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6070-#0.csv',
     '3010': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3010-#0.csv',
     '6028': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6028-#0.csv',
     '3037': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3037-#0.csv',
     '4007': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4007-#0.csv',
     '6050': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6050-#0.csv',
     '6047': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6047-#0.csv',
     '4052': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4052-#0.csv',
     '3008': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3008-#0.csv',
     '3015': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3015-#0.csv',
     '3000': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3000-#0.csv',
     '4032': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4032-#0.csv',
     '5002': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5002-#0.csv',
     '4001': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4001-#0.csv',
     '3022': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3022-#0.csv',
     '4013': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4013-#0.csv',
     '6056': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6056-#0.csv',
     '7001': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7001-#0.csv',
     '3035': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3035-#0.csv',
     '4028': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4028-#0.csv',
     '7012': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7012-#0.csv',
     '4017': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4017-#0.csv',
     '4054': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4054-#0.csv',
     '6062': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6062-#0.csv',
     '6040': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6040-#0.csv',
     '6057': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6057-#0.csv',
     '4020': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4020-#0.csv',
     '3020': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3020-#0.csv',
     '5006': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5006-#0.csv',
     '4043': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4043-#0.csv',
     '6021': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6021-#0.csv',
     '7008': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7008-#0.csv',
     '6026': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6026-#0.csv',
     '4055': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4055-#0.csv',
     '4031': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4031-#0.csv',
     '4046': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4046-#0.csv',
     '4014': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4014-#0.csv',
     '3005': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3005-#0.csv',
     '4000': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4000-#0.csv',
     '7011': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7011-#0.csv',
     '6011': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6011-#0.csv',
     '7003': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7003-#0.csv',
     '6008': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6008-#0.csv',
     '6038': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6038-#0.csv',
     '3013': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3013-#0.csv',
     '6017': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6017-#0.csv',
     '6014': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6014-#0.csv',
     '7013': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7013-#0.csv',
     '4021': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4021-#0.csv',
     '4004': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4004-#0.csv',
     '6046': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6046-#0.csv',
     '7000': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7000-#0.csv',
     '2111': '../data/raw/20260418-000722/carnet/H-series/run-17/H-2111-#0.csv',
     '6069': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6069-#0.csv',
     '4056': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4056-#0.csv',
     '6016': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6016-#0.csv',
     '6078': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6078-#0.csv',
     '3012': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3012-#0.csv',
     '4010': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4010-#0.csv',
     '6006': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6006-#0.csv',
     '4037': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4037-#0.csv',
     '300': '../data/raw/20260418-000722/carnet/H-series/run-17/H-300-#0.csv',
     '1111': '../data/raw/20260418-000722/carnet/H-series/run-17/H-1111-#0.csv',
     '3014': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3014-#0.csv',
     '6071': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6071-#0.csv',
     '7002': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7002-#0.csv',
     '6004': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6004-#0.csv',
     '3027': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3027-#0.csv',
     '6041': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6041-#0.csv',
     '4040': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4040-#0.csv',
     '6045': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6045-#0.csv',
     '5005': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5005-#0.csv',
     '4027': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4027-#0.csv',
     '4036': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4036-#0.csv',
     '4026': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4026-#0.csv',
     '6042': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6042-#0.csv',
     '4048': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4048-#0.csv',
     '6024': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6024-#0.csv',
     '6039': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6039-#0.csv',
     '4012': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4012-#0.csv',
     '6036': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6036-#0.csv',
     '4016': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4016-#0.csv',
     '3016': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3016-#0.csv',
     '6032': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6032-#0.csv',
     '3039': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3039-#0.csv',
     '3025': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3025-#0.csv',
     '6027': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6027-#0.csv',
     '6066': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6066-#0.csv',
     '5004': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5004-#0.csv',
     '6059': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6059-#0.csv',
     '6072': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6072-#0.csv',
     '6034': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6034-#0.csv',
     '3036': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3036-#0.csv',
     '6074': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6074-#0.csv',
     '4029': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4029-#0.csv',
     '6003': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6003-#0.csv',
     '3032': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3032-#0.csv',
     '6018': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6018-#0.csv',
     '6044': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6044-#0.csv',
     '3002': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3002-#0.csv',
     '3001': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3001-#0.csv',
     '6002': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6002-#0.csv',
     '4049': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4049-#0.csv',
     '6054': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6054-#0.csv',
     '3031': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3031-#0.csv',
     '6020': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6020-#0.csv',
     '4061': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4061-#0.csv',
     '3006': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3006-#0.csv',
     '4022': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4022-#0.csv',
     '3024': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3024-#0.csv',
     '6065': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6065-#0.csv',
     '6037': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6037-#0.csv',
     '3023': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3023-#0.csv',
     '6043': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6043-#0.csv',
     '4023': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4023-#0.csv',
     '3026': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3026-#0.csv',
     '6055': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6055-#0.csv',
     '4030': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4030-#0.csv',
     '3030': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3030-#0.csv',
     '3033': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3033-#0.csv',
     '4041': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4041-#0.csv',
     '6007': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6007-#0.csv',
     '4057': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4057-#0.csv',
     '6009': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6009-#0.csv',
     '4060': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4060-#0.csv',
     '6023': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6023-#0.csv',
     '4019': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4019-#0.csv',
     '6013': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6013-#0.csv',
     '5003': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5003-#0.csv',
     '4006': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4006-#0.csv',
     '6025': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6025-#0.csv',
     '4025': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4025-#0.csv',
     '4002': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4002-#0.csv',
     '3021': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3021-#0.csv',
     '6061': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6061-#0.csv',
     '7005': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7005-#0.csv',
     '6031': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6031-#0.csv',
     '4038': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4038-#0.csv',
     '4047': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4047-#0.csv',
     '3028': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3028-#0.csv',
     '3011': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3011-#0.csv',
     '4044': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4044-#0.csv',
     '3029': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3029-#0.csv',
     '6064': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6064-#0.csv',
     '4045': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4045-#0.csv',
     '6060': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6060-#0.csv',
     '3004': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3004-#0.csv',
     '4003': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4003-#0.csv',
     '6029': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6029-#0.csv',
     '6063': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6063-#0.csv',
     '6010': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6010-#0.csv',
     '3003': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3003-#0.csv',
     '4033': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4033-#0.csv',
     '4058': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4058-#0.csv',
     '6030': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6030-#0.csv',
     '6022': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6022-#0.csv',
     '4008': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4008-#0.csv',
     '6058': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6058-#0.csv',
     '7010': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7010-#0.csv',
     '1112': '../data/raw/20260418-000722/carnet/H-series/run-17/H-1112-#0.csv',
     '4005': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4005-#0.csv',
     '7004': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7004-#0.csv',
     '3041': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3041-#0.csv',
     '6067': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6067-#0.csv',
     '6048': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6048-#0.csv',
     '6077': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6077-#0.csv',
     '7009': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7009-#0.csv',
     '6005': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6005-#0.csv',
     '3034': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3034-#0.csv',
     '6012': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6012-#0.csv',
     '6068': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6068-#0.csv',
     '2112': '../data/raw/20260418-000722/carnet/H-series/run-17/H-2112-#0.csv',
     '4042': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4042-#0.csv',
     '5000': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5000-#0.csv',
     '6073': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6073-#0.csv',
     '4053': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4053-#0.csv',
     '3017': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3017-#0.csv',
     '4009': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4009-#0.csv',
     '4039': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4039-#0.csv',
     '6049': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6049-#0.csv',
     '3038': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3038-#0.csv',
     '6053': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6053-#0.csv',
     '3009': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3009-#0.csv',
     '4051': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4051-#0.csv',
     '5001': '../data/raw/20260418-000722/carnet/H-series/run-17/H-5001-#0.csv',
     '3040': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3040-#0.csv',
     '2114': '../data/raw/20260418-000722/carnet/H-series/run-17/H-2114-#0.csv',
     '4011': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4011-#0.csv',
     '4034': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4034-#0.csv',
     '4059': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4059-#0.csv',
     '6051': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6051-#0.csv',
     '4050': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4050-#0.csv',
     '3019': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3019-#0.csv',
     '4035': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4035-#0.csv',
     '4018': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4018-#0.csv',
     '6033': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6033-#0.csv',
     '3018': '../data/raw/20260418-000722/carnet/H-series/run-17/H-3018-#0.csv',
     '6076': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6076-#0.csv',
     '6000': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6000-#0.csv',
     '7006': '../data/raw/20260418-000722/carnet/H-series/run-17/H-7006-#0.csv',
     '6052': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6052-#0.csv',
     '4015': '../data/raw/20260418-000722/carnet/H-series/run-17/H-4015-#0.csv',
     '6015': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6015-#0.csv',
     '6001': '../data/raw/20260418-000722/carnet/H-series/run-17/H-6001-#0.csv'},
    '8': {'6019': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6019-#0.csv',
     '2113': '../data/raw/20260418-000722/carnet/H-series/run-8/H-2113-#0.csv',
     '6035': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6035-#0.csv',
     '3007': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3007-#0.csv',
     '7007': '../data/raw/20260418-000722/carnet/H-series/run-8/H-7007-#0.csv',
     '4024': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4024-#0.csv',
     '3042': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3042-#0.csv',
     '6075': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6075-#0.csv',
     '6070': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6070-#0.csv',
     '3010': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3010-#0.csv',
     '6028': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6028-#0.csv',
     '3037': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3037-#0.csv',
     '4007': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4007-#0.csv',
     '6050': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6050-#0.csv',
     '6047': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6047-#0.csv',
     '4052': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4052-#0.csv',
     '3008': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3008-#0.csv',
     '3015': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3015-#0.csv',
     '3000': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3000-#0.csv',
     '4032': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4032-#0.csv',
     '5002': '../data/raw/20260418-000722/carnet/H-series/run-8/H-5002-#0.csv',
     '4001': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4001-#0.csv',
     '3022': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3022-#0.csv',
     '4013': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4013-#0.csv',
     '6056': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6056-#0.csv',
     '7001': '../data/raw/20260418-000722/carnet/H-series/run-8/H-7001-#0.csv',
     '3035': '../data/raw/20260418-000722/carnet/H-series/run-8/H-3035-#0.csv',
     '4028': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4028-#0.csv',
     '7012': '../data/raw/20260418-000722/carnet/H-series/run-8/H-7012-#0.csv',
     '4017': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4017-#0.csv',
     '4054': '../data/raw/20260418-000722/carnet/H-series/run-8/H-4054-#0.csv',
     '6062': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6062-#0.csv',
     '6040': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6040-#0.csv',
     '6057': '../data/raw/20260418-000722/carnet/H-series/run-8/H-6057-#0.csv',

In [ ]:
scalability_files = find_files_for_series_and_runs_scalability(DATA_RAW_SCALABILITY)
scalability_files

{'1-50subs_x_1pub': {'H': {'p1_s9': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s9/run-10/H-1-#0.csv'}},
   'p1_s7': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s7/run-10/H-1-#0.csv'}},
   'p1_s47': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s47/run-10/H-1-#0.csv'}},
   'p1_s27': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s27/run-10/H-1-#0.csv'}},
   'p1_s2': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s2/run-10/H-1-#0.csv'}},
   'p1_s49': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s49/run-10/H-1-#0.csv'}},
   'p1_s28': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-13/H-1-#0.csv'},
    '6': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-6/H-1-#0.csv'},
    '21': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-21/H-1-#0.csv'},
    '24': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-24/H-1-#0.csv'},
    '1': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-1/H-1-#0.csv'},
    '7': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-7/H-1-#0.csv'},
    '16': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-16/H-1-#0.csv'},
    '12': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-12/H-1-#0.csv'},
    '3': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-3/H-1-#0.csv'},
    '4': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-4/H-1-#0.csv'},
    '25': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-25/H-1-#0.csv'},
    '9': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-9/H-1-#0.csv'},
    '11': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-11/H-1-#0.csv'},
    '20': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-20/H-1-#0.csv'},
    '23': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-23/H-1-#0.csv'},
    '14': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-14/H-1-#0.csv'},
    '19': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-19/H-1-#0.csv'},
    '18': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-18/H-1-#0.csv'},
    '10': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s28/run-10/H-1-#0.csv'}},
   'p1_s29': {'17': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-17/H-1-#0.csv'},
    '8': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-8/H-1-#0.csv'},
    '2': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-2/H-1-#0.csv'},
    '5': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-5/H-1-#0.csv'},
    '22': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-22/H-1-#0.csv'},
    '15': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-15/H-1-#0.csv'},
    '13': {'1': '../data/raw/20260418-000722/scalability/1-50subs_x_1pub/H-series/p1_s29/run-13/H-1-#0.csv'},

## Result file parsing and preprocessing
Parse result files to a polars data frame and add common aggregates per service, per run, per series.
- Original statistics are capitalized, computed columns are lowercase, `dur` indicates a relative duration between two timestamps, see `column_duration_pairs`.  
- Some original columns are dropped as they are not used, see `columns_to_drop`.
- All timestamps and durations are in nanoseconds.

Goal is to generate one data frame per config that contains aggregated statistics over all runs of that config and can be used for further analysis.

In [302]:
# Helpers to parse one stat file
columns_to_drop = [
    "PUBLISHER_APP_INITIALIZATION",
    "GENERATE_OFFER_NONCE_START",
    "GENERATE_OFFER_NONCE_END",
    "FIND_RECEIVE",
    "OFFER_SEND",
    "SVCB_SERVICE_REQUEST_RECEIVE",
    "SVCB_SERVICE_RESPONSE_SEND",
    "SVCB_CLIENT_REQUEST_SEND",
    "SVCB_CLIENT_REQUEST_RECEIVE",
    "SVCB_CLIENT_RESPONSE_SEND",
    "SVCB_CLIENT_RESPONSE_RECEIVE",
    "TLSA_CLIENT_REQUEST_RECEIVE",
    "TLSA_CLIENT_RESPONSE_SEND",
    "TLSA_SERVICE_REQUEST_RECEIVE",
    "TLSA_SERVICE_RESPONSE_SEND",
]

column_duration_pairs = {
    ("SUBSCRIBER_APP_INITIALIZATION_START", "SUBSCRIBER_APP_INITIALIZATION_END"): "subscriber_app_init_dur",
    ("FIND_SEND", "OFFER_RECEIVE"): "find_offer_dur",
    ("SVCB_SERVICE_REQUEST_SEND", "SVCB_SERVICE_RESPONSE_RECEIVE"): "svcb_service_dur",
    ("VALIDATE_OFFER_START", "VALIDATE_OFFER_END"): "validate_offer_dur",
    ("CLIENT_SIGN_START", "CLIENT_SIGN_END"): "client_sign_dur",
    ("OFFER_RECEIVE", "SUBSCRIBE_SEND"): "offer_to_subscribe_dur",
    ("SUBSCRIBE_SEND", "SUBSCRIBE_RECEIVE"): "subscribe_transmission_dur",
    ("TLSA_CLIENT_REQUEST_SEND", "TLSA_CLIENT_RESPONSE_RECEIVE"): "tlsa_client_dur",
    ("VERIFY_CLIENT_SIGNATURE_START", "VERIFY_CLIENT_SIGNATURE_END"): "verify_client_dur",
    ("SERVICE_SIGN_START", "SERVICE_SIGN_END"): "service_sign_dur",
    ("SUBSCRIBE_ACK_SEND", "SUBSCRIBE_ACK_RECEIVE"): "subscribeack_transmission_dur",
    ("SUBSCRIBE_SEND", "SUBSCRIBE_ACK_RECEIVE"): "subscribe_to_subscribeack_client_dur",
    ("SUBSCRIBE_RECEIVE", "SUBSCRIBE_ACK_SEND"): "subscribe_to_subscribeack_service_dur",
    ("TLSA_SERVICE_REQUEST_SEND", "TLSA_SERVICE_RESPONSE_RECEIVE"): "tlsa_service_dur",
    ("VERIFY_SERVICE_SIGNATURE_START", "VERIFY_SERVICE_SIGNATURE_END"): "verify_service_dur",
    ("OFFER_RECEIVE", "SUBSCRIBE_ACK_RECEIVE"): "offer_receive_to_subscribeack_dur",
    ("VALIDATE_OFFER_END", "SUBSCRIBE_ACK_RECEIVE"): "validate_offer_to_subscribeack_dur",
    ("OFFER_RECEIVE", "VERIFY_SERVICE_SIGNATURE_END"): "offer_receive_to_verify_service_dur",
    ("VALIDATE_OFFER_END", "VERIFY_SERVICE_SIGNATURE_END"): "validate_offer_to_verify_service_dur",
}

def preprocess_stat_file(raw_file):
    duration_exprs = [
        (pl.col(end_col) - pl.col(start_col)).alias(duration_col)
        for (start_col, end_col), duration_col in column_duration_pairs.items()
    ]
    # host_ip_expr = pl.col("HOST").map_elements(lambda x: str(ipaddress.IPv4Address(x)), return_dtype=pl.Utf8).alias("host_ip")
    return (
        pl.scan_csv(raw_file)
        .drop(columns_to_drop, strict=False)
        .with_columns(pl.selectors.numeric().replace(0, None)) # replace 0 with null for numeric columns to avoid skewing aggregates
        .with_columns(duration_exprs)
        .with_columns(
            [
                pl.max_horizontal(
                    "offer_receive_to_subscribeack_dur",
                    "offer_receive_to_verify_service_dur",
                ).alias("subscription_dur"),
                pl.max_horizontal(
                    "validate_offer_to_subscribeack_dur",
                    "validate_offer_to_verify_service_dur",
                ).alias("valid_offer_to_subscription_dur"),
                pl.min_horizontal(
                    "svcb_service_dur",
                    "tlsa_client_dur",
                    "tlsa_service_dur",
                ).alias("dns_resolution_min_dur"),
                pl.mean_horizontal(
                    "svcb_service_dur",
                    "tlsa_client_dur",
                    "tlsa_service_dur",
                ).alias("dns_resolution_mean_dur"),
                pl.max_horizontal(
                    "svcb_service_dur",
                    "tlsa_client_dur",
                    "tlsa_service_dur",
                ).alias("dns_resolution_max_dur"),
            ]
        )
        .collect()
    )

In [303]:
# helpers to parse one run with multiple service files
cols_duration = list(column_duration_pairs.values()) + [
    "subscription_dur",
    "valid_offer_to_subscription_dur",
]
cols_first_last = [
        ("SUBSCRIBER_APP_INITIALIZATION_START", "subscriber_app_initialization_start"),
        ("OFFER_RECEIVE", "offer_receive"),
        ("VALIDATE_OFFER_END", "validate_offer_end"),
        ("FIND_SEND", "find_send"),
        ("SUBSCRIBE_SEND", "subscribe_send"),
        ("SUBSCRIBE_ACK_RECEIVE", "subscribe_ack_receive"),
        ("VERIFY_SERVICE_SIGNATURE_END", "verify_service_signature_end"),
        ("SVCB_SERVICE_REQUEST_SEND", "svcb_service_request_send"),
        ("TLSA_CLIENT_REQUEST_SEND", "tlsa_client_request_send"),
        ("TLSA_SERVICE_REQUEST_SEND", "tlsa_service_request_send"),
        ("SUBSCRIBER_APP_INITIALIZATION_END", "subscriber_app_initialization_end"),
    ]

def preprocess_run_data(raw_run_files):
    # preprocess and stack all service files for one run
    all_services_df = pl.concat(
        [preprocess_stat_file(path).with_columns(pl.lit(service).alias("service")) for service, path in raw_run_files.items()],
        how="vertical_relaxed",
        rechunk=True,
    )
    # build aggregate expressions once
    first_last_exprs = [
        expr
        for col_name, alias_base in cols_first_last
        for expr in (
            pl.col(col_name).drop_nulls().min().alias(f"{alias_base}_first"),
            pl.col(col_name).drop_nulls().max().alias(f"{alias_base}_last"),
        )
    ]
    duration_exprs = [
        expr
        for col_name in cols_duration
        for expr in (
            pl.col(col_name).drop_nulls().min().alias(f"{col_name}_min"),
            pl.col(col_name).drop_nulls().mean().alias(f"{col_name}_mean"),
            pl.col(col_name).drop_nulls().std().alias(f"{col_name}_stddev"),
            pl.col(col_name).drop_nulls().max().alias(f"{col_name}_max"),
        )
    ]
    dns_exprs = [
        pl.col("dns_resolution_min_dur").drop_nulls().min().alias("dns_resolution_dur_min"),
        pl.col("dns_resolution_mean_dur").drop_nulls().mean().alias("dns_resolution_dur_mean"),
        pl.col("dns_resolution_max_dur").drop_nulls().max().alias("dns_resolution_dur_max"),
    ]
    # expression to drop everything except the columns that contain "dur"
    drop_non_duration_expr = pl.all().exclude("^.*dur.*$")
    # compute all base aggregates in one pass, then derive total durations
    return (
        all_services_df
        .select(first_last_exprs + duration_exprs + dns_exprs)
        .with_columns(
            (pl.col("subscribe_ack_receive_last") - pl.col("offer_receive_first")).alias(
                "total_offer_receive_to_subscribeack_dur"
            ),
            (pl.col("verify_service_signature_end_last") - pl.col("offer_receive_first")).alias(
                "total_offer_receive_to_verify_service_dur"
            ),
            (pl.col("subscribe_ack_receive_last") - pl.col("validate_offer_end_first")).alias(
                "total_validate_offer_to_subscribeack_dur"
            ),
            (pl.col("verify_service_signature_end_last") - pl.col("validate_offer_end_first")).alias(
                "total_validate_offer_to_verify_service_dur"
            ),
        ).drop(drop_non_duration_expr)
    ), all_services_df

In [ ]:
# helpers to parse all runs of one config 
def preprocess_config_runs(raw_config_runs):
    # preprocess and stack all runs for one config, including run number
    all_runs_df = pl.concat(
        [preprocess_run_data(data)[0].with_columns(pl.lit(runs).cast(pl.Int32).alias("run")) for runs, data in raw_config_runs.items()],
        how="vertical_relaxed",
        rechunk=True,
    )
    # create another dataframe that contains the aggregates of these runs
    
    return all_runs_df

In [ ]:
# example for file processing of one service file
df_stat = preprocess_stat_file(carnet_files['carnet']['H']['p212_s448']['18']['2114'])
df_stat

shape: (1, 49)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ HOS ┆ SUB ┆ SUB ┆ FIN ┆ OFF ┆ SVC ┆ SVC ┆ VAL ┆ VAL ┆ CLI ┆ CLI ┆ SUB ┆ SUB ┆ TLS ┆ TLS ┆ VER ┆ VER ┆ SER ┆ SER ┆ SUB ┆ SUB ┆ TLS ┆ TLS ┆ VER ┆ VER ┆ sub ┆ fin ┆ svc ┆ val ┆ cli ┆ off ┆ sub ┆ tls ┆ ver ┆ ser ┆ sub ┆ sub ┆ sub ┆ tls ┆ ver ┆ off ┆ val ┆ off ┆ val ┆ sub ┆ val ┆ dns ┆ dns ┆ dns │
│ T   ┆ SCR ┆ SCR ┆ D_S ┆ ER_ ┆ B_S ┆ B_S ┆ IDA ┆ IDA ┆ ENT ┆ ENT ┆ SCR ┆ SCR ┆ A_C ┆ A_C ┆ IFY ┆ IFY ┆ VIC ┆ VIC ┆ SCR ┆ SCR ┆ A_S ┆ A_S ┆ IFY ┆ IFY ┆ scr ┆ d_o ┆ b_s ┆ ida ┆ ent ┆ er_ ┆ scr ┆ a_c ┆ ify ┆ vic ┆ scr ┆ scr ┆ scr ┆ a_s ┆ ify ┆ er_ ┆ ida ┆ er_ ┆ ida ┆ scr ┆ id_ ┆ _re ┆ _re ┆ _re │
│ --- ┆ IBE ┆ IBE ┆ END ┆ REC ┆ ERV ┆ ERV ┆ TE_ ┆ TE_ ┆ _SI ┆ _SI ┆ IBE ┆ IBE ┆ LIE ┆ LIE ┆ _CL ┆ _CL ┆ E_S ┆ E_S ┆ IBE ┆ IBE ┆ ERV ┆ ERV ┆ _SE ┆ _SE ┆ ibe ┆ ffe ┆ erv ┆ te_ ┆ _si ┆ to_ ┆ ibe ┆ lie ┆ _cl ┆ e_s ┆ ibe ┆ ibe ┆ ibe ┆ erv ┆ _se ┆ rec ┆ te_ ┆ rec ┆ te_ ┆ ipt ┆ off ┆ sol ┆ sol ┆ sol │
│ i64 ┆ R_A ┆ R_A ┆ --- ┆ EIV ┆ ICE ┆ ICE ┆ OFF ┆ OFF ┆ GN_ ┆ GN_ ┆ _SE ┆ _RE ┆ NT_ ┆ NT_ ┆ IEN ┆ IEN ┆ IGN ┆ IGN ┆ _AC ┆ _AC ┆ ICE ┆ ICE ┆ RVI ┆ RVI ┆ r_a ┆ r_d ┆ ice ┆ off ┆ gn_ ┆ sub ┆ _tr ┆ nt_ ┆ ien ┆ ign ┆ ack ┆ _to ┆ _to ┆ ice ┆ rvi ┆ eiv ┆ off ┆ eiv ┆ off ┆ ion ┆ er_ ┆ uti ┆ uti ┆ uti │
│     ┆ PP_ ┆ PP_ ┆ i64 ┆ E   ┆ _RE ┆ _RE ┆ ER_ ┆ ER_ ┆ STA ┆ END ┆ ND  ┆ CEI ┆ REQ ┆ RES ┆ T_S ┆ T_S ┆ _ST ┆ _EN ┆ K_S ┆ K_R ┆ _RE ┆ _RE ┆ CE_ ┆ CE_ ┆ pp_ ┆ ur  ┆ _du ┆ er_ ┆ dur ┆ scr ┆ ans ┆ dur ┆ t_d ┆ _du ┆ _tr ┆ _su ┆ _su ┆ _du ┆ ce_ ┆ e_t ┆ er_ ┆ e_t ┆ er_ ┆ _du ┆ to_ ┆ on_ ┆ on_ ┆ on_ │
│     ┆ INI ┆ INI ┆     ┆ --- ┆ QUE ┆ SPO ┆ STA ┆ END ┆ RT  ┆ --- ┆ --- ┆ VE  ┆ UES ┆ PON ┆ IGN ┆ IGN ┆ ART ┆ D   ┆ END ┆ ECE ┆ QUE ┆ SPO ┆ SIG ┆ SIG ┆ ini ┆ --- ┆ r   ┆ dur ┆ --- ┆ ibe ┆ mis ┆ --- ┆ ur  ┆ r   ┆ ans ┆ bsc ┆ bsc ┆ r   ┆ dur ┆ o_s ┆ to_ ┆ o_v ┆ to_ ┆ r   ┆ sub ┆ min ┆ mea ┆ max │
│     ┆ TIA ┆ TIA ┆     ┆ i64 ┆ ST_ ┆ NSE ┆ RT  ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ T_S ┆ SE_ ┆ ATU ┆ ATU ┆ --- ┆ --- ┆ --- ┆ IVE ┆ ST_ ┆ NSE ┆ NAT ┆ NAT ┆ t_d ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ _du ┆ sio ┆ i64 ┆ --- ┆ --- ┆ mis ┆ rib ┆ rib ┆ --- ┆ --- ┆ ubs ┆ sub ┆ eri ┆ ver ┆ --- ┆ scr ┆ _du ┆ n_d ┆ _du │
│     ┆ LIZ ┆ LIZ ┆     ┆     ┆ SEN ┆ _RE ┆ --- ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ END ┆ REC ┆ RE_ ┆ RE_ ┆ i64 ┆ i64 ┆ i64 ┆ --- ┆ SEN ┆ _RE ┆ URE ┆ URE ┆ ur  ┆     ┆ i64 ┆ i64 ┆     ┆ r   ┆ n_d ┆     ┆ i64 ┆ i64 ┆ sio ┆ eac ┆ eac ┆ i64 ┆ i64 ┆ cri ┆ scr ┆ fy_ ┆ ify ┆ i64 ┆ ipt ┆ r   ┆ ur  ┆ r   │
│     ┆ ATI ┆ ATI ┆     ┆     ┆ D   ┆ CEI ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ EIV ┆ STA ┆ END ┆     ┆     ┆     ┆ i64 ┆ D   ┆ CEI ┆ _ST ┆ _EN ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ ur  ┆     ┆     ┆     ┆ n_d ┆ k_c ┆ k_s ┆     ┆     ┆ bea ┆ ibe ┆ ser ┆ _se ┆     ┆ ion ┆ --- ┆ --- ┆ --- │
│     ┆ ON_ ┆ ON_ ┆     ┆     ┆ --- ┆ VE  ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ E   ┆ RT  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ VE  ┆ ART ┆ D   ┆ i64 ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆     ┆ ur  ┆ lie ┆ erv ┆     ┆     ┆ ck_ ┆ ack ┆ vic ┆ rvi ┆     ┆ _du ┆ i64 ┆ f64 ┆ i64 │
│     ┆ …   ┆ …   ┆     ┆     ┆ i64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ --- ┆ …   ┆ …   ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆ …   ┆     ┆     ┆     │
│     ┆ --- ┆ --- ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆     ┆     ┆     │
│     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 167 ┆ 177 ┆ 177 ┆ nul ┆ nul ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 177 ┆ 152 ┆ nul ┆ 161 ┆ 319 ┆ 170 ┆ nul ┆ 119 ┆ 387 ┆ 293 ┆ 158 ┆ 478 ┆ 538 ┆ 478 ┆ 490 ┆ 243 ┆ nul ┆ 104 ┆ nul ┆ 107 ┆ nul ┆ 107 ┆ 387 ┆ 831 ┆ 161 │
│ 772 ┆ 646 ┆ 646 ┆ l   ┆ l   ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 646 ┆ 717 ┆ l   ┆ 622 ┆     ┆ 139 ┆ l   ┆ 146 ┆ 382 ┆ 046 ┆ 866 ┆ 031 ┆ 388 ┆ 671 ┆ 014 ┆ 615 ┆ l   ┆ 968 ┆ l   ┆ 505 ┆ l   ┆ 505 ┆ 382 ┆ 208 ┆ 622 │
│ 161 ┆ 419 ┆ 419 ┆     ┆     ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 419 ┆ 1   ┆     ┆ 9   ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 8   ┆ 1   ┆     ┆     ┆     ┆ 76  ┆     ┆ 09  ┆     ┆ 09  ┆     ┆ .33 ┆ 9   │
│     ┆ 875 ┆ 876 ┆     ┆     ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 879 ┆ 880 ┆ 880 ┆ 880 ┆ 880 ┆ 880 ┆ 880 ┆ 879 ┆ 879 ┆ 880 ┆ 880 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 333 ┆     │
│     ┆ 935 ┆ 087 ┆     ┆     ┆ 175 ┆ 337 ┆ 338 ┆ 338 ┆ 678 ┆ 849 ┆ 849 ┆ 861 ┆ 862 ┆ 901 ┆ 033 ┆ 062 ┆ 180 ┆ 339 ┆ 340 ┆ 387 ┆ 345 ┆ 394 ┆ 388 ┆ 413 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     │
│     ┆ 024 ┆ 741 ┆     ┆     ┆ 578 ┆ 201 ┆ 231 ┆ 263 ┆ 877 ┆ 016 ┆ 562 ┆ 477 ┆ 713 ┆ 451 ┆ 008 ┆ 313 ┆ 800 ┆ 666 ┆ 148 ┆ 951 ┆ 768 ┆ 770 ┆ 953 ┆ 314 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 8   ┆ 9   ┆     ┆     ┆ 1   ┆ 0   ┆ 7   ┆ 6   ┆ 5   ┆ 9   ┆ 4   ┆ 0   ┆ 2   ┆ 4   ┆ 4   ┆ 0   ┆ 1   ┆ 1   ┆ 1   ┆ 2   ┆ 8   ┆ 2   ┆ 0   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [ ]:
# example for processing one run with all its service files
df_run, all_services_df = preprocess_run_data(carnet_files['carnet']['H']['p212_s448']['18'])
# all_services_df
df_run

shape: (1, 91)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sub ┆ sub ┆ sub ┆ sub ┆ fin ┆ fin ┆ fin ┆ fin ┆ svc ┆ svc ┆ svc ┆ svc ┆ val ┆ val ┆ val ┆ val ┆ cli ┆ cli ┆ cli ┆ cli ┆ off ┆ off ┆ off ┆ off ┆ sub ┆ sub ┆ sub ┆ sub ┆ tls ┆ tls ┆ tls ┆ tls ┆ ver ┆ ver ┆ ver ┆ ver ┆ ser ┆ ser ┆ ser ┆ ser ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ tls ┆ tls ┆ tls ┆ tls ┆ ver ┆ ver ┆ ver ┆ ver ┆ off ┆ off ┆ off ┆ off ┆ val ┆ val ┆ val ┆ val ┆ off ┆ off ┆ off ┆ off ┆ val ┆ val ┆ val ┆ val ┆ sub ┆ sub ┆ sub ┆ sub ┆ val ┆ val ┆ val ┆ val ┆ dns ┆ dns ┆ dns ┆ tot ┆ tot ┆ tot ┆ tot │
│ scr ┆ scr ┆ scr ┆ scr ┆ d_o ┆ d_o ┆ d_o ┆ d_o ┆ b_s ┆ b_s ┆ b_s ┆ b_s ┆ ida ┆ ida ┆ ida ┆ ida ┆ ent ┆ ent ┆ ent ┆ ent ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ scr ┆ scr ┆ scr ┆ scr ┆ a_c ┆ a_c ┆ a_c ┆ a_c ┆ ify ┆ ify ┆ ify ┆ ify ┆ vic ┆ vic ┆ vic ┆ vic ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ a_s ┆ a_s ┆ a_s ┆ a_s ┆ ify ┆ ify ┆ ify ┆ ify ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ ida ┆ ida ┆ ida ┆ ida ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ ida ┆ ida ┆ ida ┆ ida ┆ scr ┆ scr ┆ scr ┆ scr ┆ id_ ┆ id_ ┆ id_ ┆ id_ ┆ _re ┆ _re ┆ _re ┆ al_ ┆ al_ ┆ al_ ┆ al_ │
│ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ffe ┆ ffe ┆ ffe ┆ ffe ┆ erv ┆ erv ┆ erv ┆ erv ┆ te_ ┆ te_ ┆ te_ ┆ te_ ┆ _si ┆ _si ┆ _si ┆ _si ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ lie ┆ lie ┆ lie ┆ lie ┆ _cl ┆ _cl ┆ _cl ┆ _cl ┆ e_s ┆ e_s ┆ e_s ┆ e_s ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ erv ┆ erv ┆ erv ┆ erv ┆ _se ┆ _se ┆ _se ┆ _se ┆ rec ┆ rec ┆ rec ┆ rec ┆ te_ ┆ te_ ┆ te_ ┆ te_ ┆ rec ┆ rec ┆ rec ┆ rec ┆ te_ ┆ te_ ┆ te_ ┆ te_ ┆ ipt ┆ ipt ┆ ipt ┆ ipt ┆ off ┆ off ┆ off ┆ off ┆ sol ┆ sol ┆ sol ┆ off ┆ off ┆ val ┆ val │
│ r_a ┆ r_a ┆ r_a ┆ r_a ┆ r_d ┆ r_d ┆ r_d ┆ r_d ┆ ice ┆ ice ┆ ice ┆ ice ┆ off ┆ off ┆ off ┆ off ┆ gn_ ┆ gn_ ┆ gn_ ┆ gn_ ┆ sub ┆ sub ┆ sub ┆ sub ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ ien ┆ ien ┆ ien ┆ ien ┆ ign ┆ ign ┆ ign ┆ ign ┆ ack ┆ ack ┆ ack ┆ ack ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ ice ┆ ice ┆ ice ┆ ice ┆ rvi ┆ rvi ┆ rvi ┆ rvi ┆ eiv ┆ eiv ┆ eiv ┆ eiv ┆ off ┆ off ┆ off ┆ off ┆ eiv ┆ eiv ┆ eiv ┆ eiv ┆ off ┆ off ┆ off ┆ off ┆ ion ┆ ion ┆ ion ┆ ion ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ uti ┆ uti ┆ uti ┆ er_ ┆ er_ ┆ ida ┆ ida │
│ pp_ ┆ pp_ ┆ pp_ ┆ pp_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ _du ┆ _du ┆ _du ┆ _du ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ dur ┆ dur ┆ dur ┆ dur ┆ scr ┆ scr ┆ scr ┆ scr ┆ ans ┆ ans ┆ ans ┆ ans ┆ dur ┆ dur ┆ dur ┆ dur ┆ t_d ┆ t_d ┆ t_d ┆ t_d ┆ _du ┆ _du ┆ _du ┆ _du ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _du ┆ _du ┆ _du ┆ _du ┆ ce_ ┆ ce_ ┆ ce_ ┆ ce_ ┆ e_t ┆ e_t ┆ e_t ┆ e_t ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ e_t ┆ e_t ┆ e_t ┆ e_t ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ _du ┆ _du ┆ _du ┆ _du ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ on_ ┆ on_ ┆ on_ ┆ rec ┆ rec ┆ te_ ┆ te_ │
│ ini ┆ ini ┆ ini ┆ ini ┆ min ┆ mea ┆ std ┆ max ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ dur ┆ dur ┆ dur ┆ dur ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ mis ┆ mis ┆ mis ┆ mis ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ ans ┆ ans ┆ ans ┆ ans ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ dur ┆ dur ┆ dur ┆ dur ┆ o_s ┆ o_s ┆ o_s ┆ o_s ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ o_v ┆ o_v ┆ o_v ┆ o_v ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ sub ┆ sub ┆ sub ┆ sub ┆ dur ┆ dur ┆ dur ┆ eiv ┆ eiv ┆ off ┆ off │
│ t_d ┆ t_d ┆ t_d ┆ t_d ┆ --- ┆ n   ┆ dev ┆ --- ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ n   ┆ an  ┆ dde ┆ x   ┆ _du ┆ _du ┆ _du ┆ _du ┆ sio ┆ sio ┆ sio ┆ sio ┆ n   ┆ an  ┆ dde ┆ x   ┆ min ┆ mea ┆ std ┆ max ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ mis ┆ mis ┆ mis ┆ mis ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ ubs ┆ ubs ┆ ubs ┆ ubs ┆ sub ┆ sub ┆ sub ┆ sub ┆ eri ┆ eri ┆ eri ┆ eri ┆ ver ┆ ver ┆ ver ┆ ver ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ scr ┆ scr ┆ scr ┆ scr ┆ _mi ┆ _me ┆ _ma ┆ e_t ┆ e_t ┆ er_ ┆ er_ │
│ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ --- ┆ --- ┆ ev  ┆ --- ┆ n   ┆ an  ┆ dde ┆ x   ┆ --- ┆ --- ┆ v   ┆ --- ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ n_d ┆ n_d ┆ n_d ┆ n_d ┆ --- ┆ --- ┆ v   ┆ --- ┆ --- ┆ n   ┆ dev ┆ --- ┆ --- ┆ --- ┆ ev  ┆ --- ┆ sio ┆ sio ┆ sio ┆ sio ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ --- ┆ --- ┆ ev  ┆ --- ┆ n   ┆ an  ┆ dde ┆ x   ┆ cri ┆ cri ┆ cri ┆ cri ┆ scr ┆ scr ┆ scr ┆ scr ┆ fy_ ┆ fy_ ┆ fy_ ┆ fy_ ┆ ify ┆ ify ┆ ify ┆ ify ┆ --- ┆ --- ┆ ev  ┆ --- ┆ ipt ┆ ipt ┆ ipt ┆ ipt ┆ n   ┆ an  ┆ x   ┆ o_s ┆ o_v ┆ to_ ┆ to_ │
│ min ┆ mea ┆ std ┆ max ┆     ┆ f64 ┆ f64 ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ --- ┆ v   ┆ --- ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ n_d ┆ n_d ┆ n_d ┆ n_d ┆ k_c ┆ k_c ┆ k_c ┆ k_c ┆ k_s ┆ k_s ┆ k_s ┆ k_s ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ --- ┆ v   ┆ --- ┆ bea ┆ bea ┆ bea ┆ bea ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ser ┆ ser ┆ ser ┆ ser ┆ _se ┆ _se ┆ _se ┆ _se ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ --- ┆ --- ┆ --- ┆ ubs ┆ eri ┆ sub ┆ ver │
│ --- ┆ n   ┆ dev ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆ ev  ┆ --- ┆ min ┆ mea ┆ std ┆ max ┆     ┆     ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ lie ┆ lie ┆ lie ┆ lie ┆ erv ┆ erv ┆ erv ┆ erv ┆     ┆     ┆ f64 ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ ck_ ┆ ck_ ┆ ck_ ┆ ck_ ┆ ack ┆ ack ┆ ack ┆ ack ┆ vic ┆ vic ┆ vic ┆ vic ┆ rvi ┆ rvi ┆ rvi ┆ rvi ┆     ┆     ┆ f64 ┆     ┆ _du ┆ _du ┆ _du ┆ _du ┆ i64 ┆ f64 ┆ i64 ┆ cri ┆ fy_ ┆ scr ┆ ify │
│ i64 ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ …   ┆ …   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   │
│     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ i64 ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 152 ┆ 1.0 ┆ 3.4 ┆ 134 ┆ 259 ┆ 4.4 ┆ 2.4 ┆ 105 ┆ 961 ┆ 3.4 ┆ 6.0 ┆ 511 ┆ 64  ┆ 145 ┆ 80. ┆ 622 ┆ 521 ┆ 789 ┆ 1.8 ┆ 384 ┆ 577 ┆ 1.7 ┆ 1.2 ┆ 117 ┆ 616 ┆ 3.1 ┆ 2.8 ┆ 953 ┆ 127 ┆ 7.1 ┆ 8.0 ┆ 410 ┆ 873 ┆ 119 ┆ 441 ┆ 304 ┆ 525 ┆ 725 ┆ 517 ┆ 449 ┆ 486 ┆ 1.5 ┆ 2.1 ┆ 131 ┆ 149 ┆ 5.8 ┆ 3.9 ┆ 318 ┆ 134 ┆ 1.2 ┆ 1.6 ┆ 265 ┆ 623 ┆ 3.1 ┆ 4.4 ┆ 231 ┆ 803 ┆ 112 ┆ 542 ┆ 808 ┆ 385 ┆ 7.6 ┆ 4.4 ┆ 328 ┆ 385 ┆ 7.6 ┆ 4.4 ┆ 328 ┆ 397 ┆ 7.6 ┆ 4.4 ┆ 328 ┆ 396 ┆ 7.6 ┆ 4.4 ┆ 328 ┆ 397 ┆ 7.6 ┆ 4.4 ┆ 328 ┆ 396 ┆ 7.6 ┆ 4.4 ┆ 328 ┆ 623 ┆ 4.5 ┆ 511 ┆ 128 ┆ 128 ┆ 128 ┆ 128 │
│ 496 ┆ 596 ┆ 994 ┆ 256 ┆ 405 ┆ 183 ┆ 332 ┆ 378 ┆ 74  ┆ 774 ┆ 642 ┆ 170 ┆     ┆ .17 ┆ 521 ┆     ┆ 430 ┆ 637 ┆ 572 ┆ 352 ┆ 886 ┆ 324 ┆ 525 ┆ 873 ┆ 38  ┆ 094 ┆ 033 ┆ 415 ┆ 385 ┆ 218 ┆ 299 ┆ 661 ┆ 19  ┆ 432 ┆ 83. ┆ 748 ┆ 110 ┆ 090 ┆ 283 ┆ 561 ┆ 80  ┆ 058 ┆ 385 ┆ 464 ┆ 432 ┆ 781 ┆ 014 ┆ 360 ┆ 409 ┆ 630 ┆ 906 ┆ 047 ┆ 03  ┆ 670 ┆ 873 ┆ 773 ┆ 55  ┆ 747 ┆ 65. ┆ 027 ┆ 515 ┆ 225 ┆ 144 ┆ 103 ┆ 112 ┆ 061 ┆ 218 ┆ 094 ┆ 144 ┆ 344 ┆ 140 ┆ 222 ┆ 741 ┆ 181 ┆ 214 ┆ 213 ┆ 144 ┆ 344 ┆ 140 ┆ 222 ┆ 741 ┆ 181 ┆ 214 ┆ 213 ┆ 03  ┆ 887 ┆ 170 ┆ 818 ┆ 830 ┆ 817 ┆ 829 │
│ 4   ┆ e7  ┆ e6  ┆ 95  ┆     ┆ e8  ┆ e8  ┆ 797 ┆     ┆ e6  ┆ e6  ┆ 66  ┆     ┆ 410 ┆ 6   ┆     ┆     ┆ .26 ┆ e6  ┆ 90  ┆     ┆ e7  ┆ e7  ┆ 819 ┆     ┆ e7  ┆ e7  ┆ 41  ┆     ┆ e6  ┆ e6  ┆ 22  ┆     ┆ .09 ┆ 585 ┆     ┆     ┆ .64 ┆ .60 ┆ 5   ┆     ┆ e7  ┆ e7  ┆ 786 ┆ 5   ┆ e7  ┆ e7  ┆ 181 ┆ 3   ┆ e7  ┆ e7  ┆ 809 ┆     ┆ e6  ┆ e6  ┆ 49  ┆     ┆ .31 ┆ 926 ┆     ┆ 9   ┆ e7  ┆ e7  ┆ 459 ┆ 9   ┆ e7  ┆ e7  ┆ 649 ┆ 0   ┆ e7  ┆ e7  ┆ 528 ┆ 0   ┆ e7  ┆ e7  ┆ 718 ┆ 0   ┆ e7  ┆ e7  ┆ 528 ┆ 0   ┆ e7  ┆ e7  ┆ 718 ┆     ┆ e6  ┆ 66  ┆ 988 ┆ 402 ┆ 966 ┆ 380 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆ 785 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 151 ┆ 522 ┆     ┆     ┆ 285 ┆ 342 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 696 ┆ 567 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 9   ┆ 6   ┆ 8   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [ ]:
# example for processing all runs of one config
df_config = preprocess_config_runs(carnet_files['carnet']['H']['p212_s448'])
df_config

shape: (25, 92)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sub ┆ sub ┆ sub ┆ sub ┆ fin ┆ fin ┆ fin ┆ fin ┆ svc ┆ svc ┆ svc ┆ svc ┆ val ┆ val ┆ val ┆ val ┆ cli ┆ cli ┆ cli ┆ cli ┆ off ┆ off ┆ off ┆ off ┆ sub ┆ sub ┆ sub ┆ sub ┆ tls ┆ tls ┆ tls ┆ tls ┆ ver ┆ ver ┆ ver ┆ ver ┆ ser ┆ ser ┆ ser ┆ ser ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ sub ┆ tls ┆ tls ┆ tls ┆ tls ┆ ver ┆ ver ┆ ver ┆ ver ┆ off ┆ off ┆ off ┆ off ┆ val ┆ val ┆ val ┆ val ┆ off ┆ off ┆ off ┆ off ┆ val ┆ val ┆ val ┆ val ┆ sub ┆ sub ┆ sub ┆ sub ┆ val ┆ val ┆ val ┆ val ┆ dns ┆ dns ┆ dns ┆ tot ┆ tot ┆ tot ┆ tot ┆ run │
│ scr ┆ scr ┆ scr ┆ scr ┆ d_o ┆ d_o ┆ d_o ┆ d_o ┆ b_s ┆ b_s ┆ b_s ┆ b_s ┆ ida ┆ ida ┆ ida ┆ ida ┆ ent ┆ ent ┆ ent ┆ ent ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ scr ┆ scr ┆ scr ┆ scr ┆ a_c ┆ a_c ┆ a_c ┆ a_c ┆ ify ┆ ify ┆ ify ┆ ify ┆ vic ┆ vic ┆ vic ┆ vic ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ scr ┆ a_s ┆ a_s ┆ a_s ┆ a_s ┆ ify ┆ ify ┆ ify ┆ ify ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ ida ┆ ida ┆ ida ┆ ida ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ ida ┆ ida ┆ ida ┆ ida ┆ scr ┆ scr ┆ scr ┆ scr ┆ id_ ┆ id_ ┆ id_ ┆ id_ ┆ _re ┆ _re ┆ _re ┆ al_ ┆ al_ ┆ al_ ┆ al_ ┆ --- │
│ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ffe ┆ ffe ┆ ffe ┆ ffe ┆ erv ┆ erv ┆ erv ┆ erv ┆ te_ ┆ te_ ┆ te_ ┆ te_ ┆ _si ┆ _si ┆ _si ┆ _si ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ lie ┆ lie ┆ lie ┆ lie ┆ _cl ┆ _cl ┆ _cl ┆ _cl ┆ e_s ┆ e_s ┆ e_s ┆ e_s ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ erv ┆ erv ┆ erv ┆ erv ┆ _se ┆ _se ┆ _se ┆ _se ┆ rec ┆ rec ┆ rec ┆ rec ┆ te_ ┆ te_ ┆ te_ ┆ te_ ┆ rec ┆ rec ┆ rec ┆ rec ┆ te_ ┆ te_ ┆ te_ ┆ te_ ┆ ipt ┆ ipt ┆ ipt ┆ ipt ┆ off ┆ off ┆ off ┆ off ┆ sol ┆ sol ┆ sol ┆ off ┆ off ┆ val ┆ val ┆ i32 │
│ r_a ┆ r_a ┆ r_a ┆ r_a ┆ r_d ┆ r_d ┆ r_d ┆ r_d ┆ ice ┆ ice ┆ ice ┆ ice ┆ off ┆ off ┆ off ┆ off ┆ gn_ ┆ gn_ ┆ gn_ ┆ gn_ ┆ sub ┆ sub ┆ sub ┆ sub ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ ien ┆ ien ┆ ien ┆ ien ┆ ign ┆ ign ┆ ign ┆ ign ┆ ack ┆ ack ┆ ack ┆ ack ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ _to ┆ ice ┆ ice ┆ ice ┆ ice ┆ rvi ┆ rvi ┆ rvi ┆ rvi ┆ eiv ┆ eiv ┆ eiv ┆ eiv ┆ off ┆ off ┆ off ┆ off ┆ eiv ┆ eiv ┆ eiv ┆ eiv ┆ off ┆ off ┆ off ┆ off ┆ ion ┆ ion ┆ ion ┆ ion ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ uti ┆ uti ┆ uti ┆ er_ ┆ er_ ┆ ida ┆ ida ┆     │
│ pp_ ┆ pp_ ┆ pp_ ┆ pp_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ _du ┆ _du ┆ _du ┆ _du ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ dur ┆ dur ┆ dur ┆ dur ┆ scr ┆ scr ┆ scr ┆ scr ┆ ans ┆ ans ┆ ans ┆ ans ┆ dur ┆ dur ┆ dur ┆ dur ┆ t_d ┆ t_d ┆ t_d ┆ t_d ┆ _du ┆ _du ┆ _du ┆ _du ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _su ┆ _du ┆ _du ┆ _du ┆ _du ┆ ce_ ┆ ce_ ┆ ce_ ┆ ce_ ┆ e_t ┆ e_t ┆ e_t ┆ e_t ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ e_t ┆ e_t ┆ e_t ┆ e_t ┆ er_ ┆ er_ ┆ er_ ┆ er_ ┆ _du ┆ _du ┆ _du ┆ _du ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ on_ ┆ on_ ┆ on_ ┆ rec ┆ rec ┆ te_ ┆ te_ ┆     │
│ ini ┆ ini ┆ ini ┆ ini ┆ min ┆ mea ┆ std ┆ max ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ dur ┆ dur ┆ dur ┆ dur ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ mis ┆ mis ┆ mis ┆ mis ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ ans ┆ ans ┆ ans ┆ ans ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ bsc ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ dur ┆ dur ┆ dur ┆ dur ┆ o_s ┆ o_s ┆ o_s ┆ o_s ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ o_v ┆ o_v ┆ o_v ┆ o_v ┆ to_ ┆ to_ ┆ to_ ┆ to_ ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ sub ┆ sub ┆ sub ┆ sub ┆ dur ┆ dur ┆ dur ┆ eiv ┆ eiv ┆ off ┆ off ┆     │
│ t_d ┆ t_d ┆ t_d ┆ t_d ┆ --- ┆ n   ┆ dev ┆ --- ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ n   ┆ an  ┆ dde ┆ x   ┆ _du ┆ _du ┆ _du ┆ _du ┆ sio ┆ sio ┆ sio ┆ sio ┆ n   ┆ an  ┆ dde ┆ x   ┆ min ┆ mea ┆ std ┆ max ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ mis ┆ mis ┆ mis ┆ mis ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ rib ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ _mi ┆ _me ┆ _st ┆ _ma ┆ ubs ┆ ubs ┆ ubs ┆ ubs ┆ sub ┆ sub ┆ sub ┆ sub ┆ eri ┆ eri ┆ eri ┆ eri ┆ ver ┆ ver ┆ ver ┆ ver ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ scr ┆ scr ┆ scr ┆ scr ┆ _mi ┆ _me ┆ _ma ┆ e_t ┆ e_t ┆ er_ ┆ er_ ┆     │
│ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ --- ┆ --- ┆ ev  ┆ --- ┆ n   ┆ an  ┆ dde ┆ x   ┆ --- ┆ --- ┆ v   ┆ --- ┆ r_m ┆ r_m ┆ r_s ┆ r_m ┆ n_d ┆ n_d ┆ n_d ┆ n_d ┆ --- ┆ --- ┆ v   ┆ --- ┆ --- ┆ n   ┆ dev ┆ --- ┆ --- ┆ --- ┆ ev  ┆ --- ┆ sio ┆ sio ┆ sio ┆ sio ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ eac ┆ --- ┆ --- ┆ ev  ┆ --- ┆ n   ┆ an  ┆ dde ┆ x   ┆ cri ┆ cri ┆ cri ┆ cri ┆ scr ┆ scr ┆ scr ┆ scr ┆ fy_ ┆ fy_ ┆ fy_ ┆ fy_ ┆ ify ┆ ify ┆ ify ┆ ify ┆ --- ┆ --- ┆ ev  ┆ --- ┆ ipt ┆ ipt ┆ ipt ┆ ipt ┆ n   ┆ an  ┆ x   ┆ o_s ┆ o_v ┆ to_ ┆ to_ ┆     │
│ min ┆ mea ┆ std ┆ max ┆     ┆ f64 ┆ f64 ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ --- ┆ v   ┆ --- ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ in  ┆ ean ┆ tdd ┆ ax  ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ n_d ┆ n_d ┆ n_d ┆ n_d ┆ k_c ┆ k_c ┆ k_c ┆ k_c ┆ k_s ┆ k_s ┆ k_s ┆ k_s ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ --- ┆ v   ┆ --- ┆ bea ┆ bea ┆ bea ┆ bea ┆ ibe ┆ ibe ┆ ibe ┆ ibe ┆ ser ┆ ser ┆ ser ┆ ser ┆ _se ┆ _se ┆ _se ┆ _se ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ --- ┆ --- ┆ --- ┆ ubs ┆ eri ┆ sub ┆ ver ┆     │
│ --- ┆ n   ┆ dev ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆ ev  ┆ --- ┆ min ┆ mea ┆ std ┆ max ┆     ┆     ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ ur_ ┆ ur_ ┆ ur_ ┆ ur_ ┆ lie ┆ lie ┆ lie ┆ lie ┆ erv ┆ erv ┆ erv ┆ erv ┆     ┆     ┆ f64 ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ ck_ ┆ ck_ ┆ ck_ ┆ ck_ ┆ ack ┆ ack ┆ ack ┆ ack ┆ vic ┆ vic ┆ vic ┆ vic ┆ rvi ┆ rvi ┆ rvi ┆ rvi ┆     ┆     ┆ f64 ┆     ┆ _du ┆ _du ┆ _du ┆ _du ┆ i64 ┆ f64 ┆ i64 ┆ cri ┆ fy_ ┆ scr ┆ ify ┆     │
│ i64 ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ --- ┆ i64 ┆ --- ┆ …   ┆ …   ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆     │
│     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ i64 ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆     ┆     ┆     ┆     ┆ i64 ┆ f64 ┆ f64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆ i64 ┆ i64 ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 140 ┆ 1.0 ┆ 3.4 ┆ 130 ┆ 204 ┆ 3.3 ┆ 2.5 ┆ 104 ┆ 673 ┆ 4.0 ┆ 6.6 ┆ 519 ┆ 59  ┆ 704 ┆ 146 ┆ 309 ┆ 523 ┆ 666 ┆ 491 ┆ 559 ┆ 602 ┆ 1.8 ┆ 1.1 ┆ 503 ┆ 851 ┆ 4.7 ┆ 3.6 ┆ 108 ┆ 871 ┆ 1.6 ┆ 1.6 ┆ 510 ┆ 874 ┆ 136 ┆ 219 ┆ 335 ┆ 528 ┆ 742 ┆ 568 ┆ 590 ┆ 483 ┆ 2.2 ┆ 2.6 ┆ 930 ┆ 227 ┆ 9.1 ┆ 5.3 ┆ 420 ┆ 138 ┆ 2.2 ┆ 2.3 ┆ 352 ┆ 453 ┆ 3.5 ┆ 5.7 ┆ 361 ┆ 802 ┆ 144 ┆ 590 ┆ 124 ┆ 606 ┆ 1.1 ┆ 6.2 ┆ 444 ┆ 605 ┆ 1.1 ┆ 6.2 ┆ 444 ┆ 663 ┆ 1.1 ┆ 6.2 ┆ 444 ┆ 662 ┆ 1.1 ┆ 6.2 ┆ 444 ┆ 663 ┆ 1.1 ┆ 6.2 ┆ 444 ┆ 662 ┆ 1.1 ┆ 6.2 ┆ 444 ┆ 453 ┆ 8.0 ┆ 519 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 17  │
│ 592 ┆ 548 ┆ 895 ┆ 371 ┆ 930 ┆ 209 ┆ 621 ┆ 165 ┆ 31  ┆ 249 ┆ 267 ┆ 799 ┆     ┆ 1.9 ┆ 074 ┆ 195 ┆ 351 ┆ 548 ┆ 774 ┆ 300 ┆ 944 ┆ 765 ┆ 805 ┆ 405 ┆ 95  ┆ 095 ┆ 369 ┆ 014 ┆ 10  ┆ 561 ┆ 493 ┆ 872 ┆ 57  ┆ 647 ┆ 343 ┆ 729 ┆ 059 ┆ 901 ┆ 879 ┆ 187 ┆ 14  ┆ 365 ┆ 524 ┆ 410 ┆ 313 ┆ 699 ┆ 768 ┆ 912 ┆ 529 ┆ 239 ┆ 926 ┆ 479 ┆ 91  ┆ 106 ┆ 051 ┆ 466 ┆ 79  ┆ 634 ┆ 189 ┆ 276 ┆ 479 ┆ 046 ┆ 394 ┆ 064 ┆ 512 ┆ 045 ┆ 397 ┆ 062 ┆ 337 ┆ 062 ┆ 361 ┆ 176 ┆ 371 ┆ 060 ┆ 364 ┆ 173 ┆ 337 ┆ 062 ┆ 361 ┆ 176 ┆ 371 ┆ 060 ┆ 364 ┆ 173 ┆ 91  ┆ 322 ┆ 799 ┆ 522 ┆ 531 ┆ 521 ┆ 530 ┆     │
│ 9   ┆ e7  ┆ e6  ┆ 39  ┆     ┆ e8  ┆ e8  ┆ 557 ┆     ┆ e6  ┆ e6  ┆ 90  ┆     ┆ 308 ┆ .43 ┆ 3   ┆     ┆ .56 ┆ .65 ┆ 6   ┆     ┆ e7  ┆ e7  ┆ 24  ┆     ┆ e7  ┆ e7  ┆ 645 ┆     ┆ e7  ┆ e7  ┆ 14  ┆     ┆ .89 ┆ .73 ┆ 6   ┆     ┆ .29 ┆ .70 ┆ 0   ┆     ┆ e7  ┆ e7  ┆ 74  ┆ 7   ┆ e7  ┆ e7  ┆ 987 ┆ 2   ┆ e7  ┆ e7  ┆ 127 ┆     ┆ e6  ┆ e6  ┆ 42  ┆     ┆ .07 ┆ .79 ┆ 72  ┆ 1   ┆ e8  ┆ e7  ┆ 923 ┆ 9   ┆ e8  ┆ e7  ┆ 337 ┆ 3   ┆ e8  ┆ e7  ┆ 353 ┆ 1   ┆ e8  ┆ e7  ┆ 767 ┆ 3   ┆ e8  ┆ e7  ┆ 353 ┆ 1   ┆ e8  ┆ e7  ┆ 767 ┆     ┆ e6  ┆ 90  ┆ 516 ┆ 809 ┆ 550 ┆ 842 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆ 04  ┆ 873 ┆     ┆     ┆ 25  ┆ 214 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 062 ┆ 926 ┆     ┆     ┆ 464 ┆ 800 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 812 ┆ 722 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 1   ┆ 6   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 8   ┆     ┆     ┆ 3   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 140 ┆ 1.2 ┆ 4.6 ┆ 166 ┆ 247 ┆ 3.7 ┆ 2.1 ┆ 109 ┆ 933 ┆ 3.1 ┆ 5.3 ┆ 418 ┆ 58  ┆ 163 ┆ 108 ┆ 121 ┆ 512 ┆ 1.0 ┆ 2.7 ┆ 470 ┆ 566 ┆ 1.7 ┆ 1.4 ┆ 101 ┆ 711 ┆ 2.6 ┆ 1.6 ┆ 102 ┆ 106 ┆ 7.1 ┆ 7.5 ┆ 516 ┆ 889 ┆ 124 ┆ 739 ┆ 133 ┆ 523 ┆ 791 ┆ 773 ┆ 971 ┆ 624 ┆ 1.1 ┆ 9.7 ┆ 543 ┆ 260 ┆ 4.9 ┆ 1.9 ┆ 130 ┆ 130 ┆ 1.1 ┆ 9.0 ┆ 547 ┆ 642 ┆ 2.2 ┆ 3.6 ┆ 302 ┆ 824 ┆ 117 ┆ 772 ┆ 149 ┆ 636 ┆ 6.6 ┆ 2.6 ┆ 160 ┆ 635 ┆ 6.6 ┆ 2.7 ┆ 208 ┆ 650 ┆ 6.6 ┆ 2.6 ┆ 160 ┆ 649 ┆ 6.7 ┆ 2.7 ┆ 208 ┆ 650 ┆ 6.6 ┆ 2.6 ┆ 160 ┆ 649 ┆ 6.7 ┆ 2.7 ┆ 208 ┆ 642 ┆ 4.1 ┆ 516 ┆ 123 ┆ 123 ┆ 123 ┆ 123 ┆ 8   │
│ 876 ┆ 346 ┆ 412 ┆ 814 ┆ 525 ┆ 853 ┆ 029 ┆ 625 ┆ 64  ┆ 659 ┆ 112 ┆ 591 ┆     ┆ .46 ┆ .73 ┆ 4   ┆ 181 ┆ 151 ┆ 479 ┆ 740 ┆ 023 ┆ 055 ┆ 644 ┆ 969 ┆ 08  ┆ 505 ┆ 626 ┆ 786 ┆ 124 ┆ 507 ┆ 215 ┆ 357 ┆ 47  ┆ 780 ┆ 20. ┆ 160 ┆ 387 ┆ 202 ┆ 730 ┆ 307 ┆ 10  ┆ 610 ┆ 407 ┆ 771 ┆ 514 ┆ 438 ┆ 556 ┆ 361 ┆ 740 ┆ 323 ┆ 970 ┆ 169 ┆ 38  ┆ 138 ┆ 878 ┆ 019 ┆ 54  ┆ 069 ┆ 16. ┆ 111 ┆ 778 ┆ 493 ┆ 415 ┆ 658 ┆ 599 ┆ 927 ┆ 119 ┆ 380 ┆ 263 ┆ 617 ┆ 424 ┆ 876 ┆ 084 ┆ 051 ┆ 129 ┆ 627 ┆ 263 ┆ 617 ┆ 424 ┆ 876 ┆ 084 ┆ 051 ┆ 129 ┆ 627 ┆ 38  ┆ 768 ┆ 357 ┆ 117 ┆ 127 ┆ 116 ┆ 126 ┆     │
│ 9   ┆ e7  ┆ e6  ┆ 51  ┆     ┆ e8  ┆ e8  ┆ 842 ┆     ┆ e6  ┆ e6  ┆ 64  ┆     ┆ 205 ┆ 551 ┆     ┆     ┆ e6  ┆ e6  ┆ 20  ┆     ┆ e7  ┆ e7  ┆ 151 ┆     ┆ e7  ┆ e7  ┆ 280 ┆     ┆ e6  ┆ e6  ┆ 50  ┆     ┆ .39 ┆ 750 ┆ 0   ┆     ┆ .14 ┆ .82 ┆ 6   ┆     ┆ e7  ┆ e6  ┆ 47  ┆ 5   ┆ e7  ┆ e7  ┆ 798 ┆ 6   ┆ e7  ┆ e6  ┆ 00  ┆     ┆ e6  ┆ e6  ┆ 74  ┆     ┆ .53 ┆ 482 ┆ 9   ┆ 6   ┆ e7  ┆ e7  ┆ 720 ┆ 8   ┆ e7  ┆ e7  ┆ 719 ┆ 0   ┆ e7  ┆ e7  ┆ 318 ┆ 2   ┆ e7  ┆ e7  ┆ 887 ┆ 0   ┆ e7  ┆ e7  ┆ 318 ┆ 2   ┆ e7  ┆ e7  ┆ 887 ┆     ┆ e6  ┆ 50  ┆ 736 ┆ 200 ┆ 557 ┆ 021 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 955 ┆ 609 ┆     ┆     ┆ 508 ┆ 803 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 125 ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 4   ┆ 8   ┆ 6   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 139 ┆ 1.0 ┆ 3.5 ┆ 130 ┆ 650 ┆ 4.1 ┆ 2.4 ┆ 106 ┆ 130 ┆ 6.1 ┆ 1.0 ┆ 848 ┆ 64  ┆ 161 ┆ 245 ┆ 499 ┆ 524 ┆ 810 ┆ 1.0 ┆ 132 ┆ 569 ┆ 1.7 ┆ 1.2 ┆ 601 ┆ 832 ┆ 3.0 ┆ 2.3 ┆ 112 ┆ 103 ┆ 1.1 ┆ 1.3 ┆ 583 ┆ 865 ┆ 134 ┆ 138 ┆ 282 ┆ 524 ┆ 728 ┆ 526 ┆ 508 ┆ 526 ┆ 1.5 ┆ 1.4 ┆ 729 ┆ 381 ┆ 6.2 ┆ 2.2 ┆ 141 ┆ 138 ┆ 1.5 ┆ 1.4 ┆ 719 ┆ 902 ┆ 5.4 ┆ 9.3 ┆ 759 ┆ 798 ┆ 113 ┆ 472 ┆ 610 ┆ 628 ┆ 7.9 ┆ 2.9 ┆ 152 ┆ 628 ┆ 7.9 ┆ 2.9 ┆ 152 ┆ 691 ┆ 7.9 ┆ 2.9 ┆ 152 ┆ 690 ┆ 7.9 ┆ 2.9 ┆ 152 ┆ 691 ┆ 7.9 ┆ 2.9 ┆ 152 ┆ 690 ┆ 7.9 ┆ 2.9 ┆ 152 ┆ 902 ┆ 7.8 ┆ 848 ┆ 121 ┆ 121 ┆ 122 ┆ 122 ┆ 2   │
│ 971 ┆ 746 ┆ 700 ┆ 819 ┆ 195 ┆ 600 ┆ 384 ┆ 639 ┆ 217 ┆ 884 ┆ 866 ┆ 909 ┆     ┆ .07 ┆ .59 ┆ 5   ┆ 419 ┆ 280 ┆ 126 ┆ 319 ┆ 509 ┆ 080 ┆ 048 ┆ 242 ┆ 53  ┆ 922 ┆ 623 ┆ 921 ┆ 753 ┆ 860 ┆ 787 ┆ 681 ┆ 82  ┆ 939 ┆ 670 ┆ 184 ┆ 775 ┆ 832 ┆ 471 ┆ 058 ┆ 06  ┆ 544 ┆ 976 ┆ 010 ┆ 667 ┆ 413 ┆ 757 ┆ 366 ┆ 983 ┆ 947 ┆ 841 ┆ 582 ┆ 20  ┆ 428 ┆ 035 ┆ 378 ┆ 68  ┆ 176 ┆ 12. ┆ 995 ┆ 893 ┆ 493 ┆ 575 ┆ 049 ┆ 213 ┆ 617 ┆ 391 ┆ 043 ┆ 114 ┆ 614 ┆ 569 ┆ 167 ┆ 434 ┆ 738 ┆ 385 ┆ 161 ┆ 114 ┆ 614 ┆ 569 ┆ 167 ┆ 434 ┆ 738 ┆ 385 ┆ 161 ┆ 20  ┆ 302 ┆ 909 ┆ 602 ┆ 611 ┆ 785 ┆ 794 ┆     │
│ 4   ┆ e7  ┆ e6  ┆ 77  ┆     ┆ e8  ┆ e8  ┆ 013 ┆     ┆ e6  ┆ e7  ┆ 30  ┆     ┆ 812 ┆ 94  ┆     ┆     ┆ .54 ┆ e6  ┆ 93  ┆     ┆ e7  ┆ e7  ┆ 98  ┆     ┆ e7  ┆ e7  ┆ 342 ┆     ┆ e7  ┆ e7  ┆ 99  ┆     ┆ .46 ┆ .03 ┆ 3   ┆     ┆ .36 ┆ .14 ┆ 6   ┆     ┆ e7  ┆ e7  ┆ 67  ┆ 6   ┆ e7  ┆ e7  ┆ 561 ┆ 1   ┆ e7  ┆ e7  ┆ 92  ┆     ┆ e6  ┆ e6  ┆ 09  ┆     ┆ .54 ┆ 986 ┆     ┆ 1   ┆ e7  ┆ e7  ┆ 503 ┆ 2   ┆ e7  ┆ e7  ┆ 426 ┆ 1   ┆ e7  ┆ e7  ┆ 310 ┆ 2   ┆ e7  ┆ e7  ┆ 233 ┆ 1   ┆ e7  ┆ e7  ┆ 310 ┆ 2   ┆ e7  ┆ e7  ┆ 233 ┆     ┆ e6  ┆ 30  ┆ 332 ┆ 255 ┆ 890 ┆ 813 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆ 241 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 875 ┆ 770 ┆     ┆     ┆ 383 ┆ 353 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 464 ┆ 768 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 4   ┆ 7   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ 9   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 139 ┆ 1.1 ┆ 4.0 ┆ 151 ┆ 205 ┆ 3.2 ┆ 2.6 ┆ 107 ┆ 509 ┆ 4.0 ┆ 9.0 ┆ 681 ┆ 59  ┆ 140 ┆ 96. ┆ 102 ┆ 521 ┆ 836 ┆ 1.0 ┆ 137 ┆ 560 ┆ 1.6 ┆ 1.0 ┆ 511 ┆ 643 ┆ 3.8 ┆ 4.2 ┆ 128 ┆ 120 ┆ 7.9 ┆ 9.5 ┆ 422 ┆ 843 ┆ 123 ┆ 558 ┆ 719 ┆ 520 ┆ 748 ┆ 601 ┆ 569 ┆ 530 ┆ 2.5 ┆ 2.6 ┆ 884 ┆ 286 ┆ 7.6 ┆ 5.8 ┆ 230 ┆ 133 ┆ 1.2 ┆ 1.3 ┆ 129 ┆ 490 ┆ 2.5 ┆ 5.0 ┆ 377 ┆ 809 ┆ 116 ┆ 615 ┆ 812 ┆ 703 ┆ 9.3 ┆ 6.6 ┆ 261 ┆ 703 ┆ 9.3 ┆ 6.6 ┆ 261 ┆ 713 ┆ 9.3 ┆ 6.6 ┆ 261 ┆ 712 ┆ 9.3 ┆ 6.6 ┆ 261 ┆ 713 ┆ 9.3 ┆ 6.6 ┆ 261 ┆ 712 ┆ 9.3 ┆ 6.6 ┆ 261 ┆ 490 ┆ 4.8 ┆ 681 ┆ 125 ┆ 125 ┆ 125 ┆ 125 ┆ 5   │
│ 278 ┆ 366 ┆ 915 ┆ 546 ┆ 99  ┆ 421 ┆ 591 ┆ 502 ┆ 55  ┆ 294 ┆ 130 ┆ 655 ┆     ┆ .49 ┆ 327 ┆ 3   ┆ 310 ┆ 093 ┆ 575 ┆ 333 ┆ 833 ┆ 613 ┆ 507 ┆ 242 ┆ 61  ┆ 476 ┆ 351 ┆ 334 ┆ 746 ┆ 872 ┆ 181 ┆ 518 ┆ 14  ┆ 597 ┆ 85. ┆ 445 ┆ 750 ┆ 786 ┆ 703 ┆ 739 ┆ 87  ┆ 472 ┆ 158 ┆ 649 ┆ 302 ┆ 620 ┆ 784 ┆ 579 ┆ 323 ┆ 672 ┆ 139 ┆ 232 ┆ 14  ┆ 904 ┆ 159 ┆ 421 ┆ 20  ┆ 300 ┆ 78. ┆ 994 ┆ 589 ┆ 233 ┆ 651 ┆ 447 ┆ 235 ┆ 206 ┆ 668 ┆ 445 ┆ 015 ┆ 358 ┆ 640 ┆ 578 ┆ 661 ┆ 330 ┆ 657 ┆ 575 ┆ 015 ┆ 358 ┆ 640 ┆ 578 ┆ 661 ┆ 330 ┆ 657 ┆ 575 ┆ 14  ┆ 690 ┆ 655 ┆ 961 ┆ 970 ┆ 960 ┆ 970 ┆     │
│ 5   ┆ e7  ┆ e6  ┆ 78  ┆     ┆ e8  ┆ e8  ┆ 470 ┆     ┆ e6  ┆ e6  ┆ 09  ┆     ┆ 330 ┆ 578 ┆     ┆     ┆ .57 ┆ e6  ┆ 08  ┆     ┆ e7  ┆ e7  ┆ 56  ┆     ┆ e7  ┆ e7  ┆ 161 ┆     ┆ e6  ┆ e6  ┆ 22  ┆     ┆ .83 ┆ 562 ┆     ┆     ┆ .51 ┆ .05 ┆ 5   ┆     ┆ e7  ┆ e7  ┆ 34  ┆ 3   ┆ e7  ┆ e7  ┆ 159 ┆ 0   ┆ e7  ┆ e7  ┆ 037 ┆     ┆ e6  ┆ e6  ┆ 70  ┆     ┆ .18 ┆ 437 ┆     ┆ 4   ┆ e7  ┆ e7  ┆ 872 ┆ 5   ┆ e7  ┆ e7  ┆ 125 ┆ 4   ┆ e7  ┆ e7  ┆ 240 ┆ 5   ┆ e7  ┆ e7  ┆ 493 ┆ 4   ┆ e7  ┆ e7  ┆ 240 ┆ 5   ┆ e7  ┆ e7  ┆ 493 ┆     ┆ e6  ┆ 09  ┆ 702 ┆ 856 ┆ 924 ┆ 078 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 589 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 705 ┆ 792 ┆     ┆     ┆ 785 ┆ 590 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 303 ┆ 556 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆ 2   ┆ 2   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 154 ┆ 1.0 ┆ 3.4 ┆ 133 ┆ 179 ┆ 3.3 ┆ 2.0 ┆ 110 ┆ 887 ┆ 6.2 ┆ 1.0 ┆ 938 ┆ 60  ┆ 129 ┆ 75. ┆ 104 ┆ 521 ┆ 766 ┆ 894 ┆ 120 ┆ 573 ┆ 1.8 ┆ 1.2 ┆ 541 ┆ 911 ┆ 3.5 ┆ 3.5 ┆ 124 ┆ 926 ┆ 1.6 ┆ 1.7 ┆ 712 ┆ 885 ┆ 131 ┆ 136 ┆ 274 ┆ 527 ┆ 728 ┆ 492 ┆ 470 ┆ 546 ┆ 1.2 ┆ 1.3 ┆ 551 ┆ 229 ┆ 6.7 ┆ 4.3 ┆ 158 ┆ 133 ┆ 1.9 ┆ 1.7 ┆ 786 ┆ 561 ┆ 6.6 ┆ 1.3 ┆ 100 ┆ 810 ┆ 112 ┆ 394 ┆ 306 ┆ 102 ┆ 8.6 ┆ 4.8 ┆ 174 ┆ 102 ┆ 8.6 ┆ 4.8 ┆ 174 ┆ 104 ┆ 8.6 ┆ 4.8 ┆ 174 ┆ 104 ┆ 8.6 ┆ 4.8 ┆ 174 ┆ 104 ┆ 8.6 ┆ 4.8 ┆ 174 ┆ 104 ┆ 8.6 ┆ 4.8 ┆ 174 ┆ 561 ┆ 9.7 ┆ 100 ┆ 124 ┆ 124 ┆ 124 ┆ 124 ┆ 22  │

In [ ]:
# export df_config to parquet for use in analysis notebook